[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bogde/HX711@^0.7.5
    ; olikraus/U8g2@^2.35.19   ; Uncomment when display is wired (Feature #2)

[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = 192.168.1.XXX   ; Replace with ESP32 IP address
